### PR TITLE
Signed status response code from @jvandesande and fixed bug with invalid locales, updated example to use iDEAL v2

### PR DESCRIPTION
**Pull request by AngeloG**
Locale for `LC_NUMERIC` needs to be `en_US` or `en_US.UTF-8` for floating point numbers to be written with periods. If commas are used (such as with `nl_NL` or `nl_NL.UTF-8`), the Buckaroo server throws an internal error.

Also updated the example to use iDEAL v2.

### CODE REVIEW

**Comment by AngeloG** [comment]
Poking @joostfaassen. Is this project abandoned?

**Comment by joostfaassen** [comment]
Thanks @AngeloG and @jvandesande, it's merged!

**Comment by AngeloG** [comment]
Nice! It might be worth tagging as well, to update the library on packagist.

**Comment by joostfaassen** [comment]
Done, it's now tagged at v1.4
Cheers!

**Pull request merged**
